version: "3.8"

services:
  web:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - REDIS_HOST=redis  # Docker container hostname
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy  # Ensure Redis is ready before Django starts
    networks:
      - visitor_management_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - visitor_management_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s

networks:
  visitor_management_network:
    driver: bridge
