# Generated by Django 4.0.5 on 2025-02-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='company_address',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='company_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose_of_visit',
            field=models.CharField(default='Na', max_length=100),
        ),
    ]
