# Generated by Django 4.0.5 on 2025-02-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
