# Generated by Django 4.0.5 on 2025-02-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_delete_mymodel_delete_post'),
        ('demo', '0002_mymodel'),
    ]

    operations = [
    ]
